import { Adversary } from './types';
import { allGameItems } from './itemsData';

export const originalAdversaries: Adversary[] = [
  {
    id: 'boss_01',
    number: 1,
    name: 'Espantalho de Palha Fortificada',
    title: 'Manequim de Teste da Academia',
    level: 1,
    maxHp: 250,
    currentHp: 250,
    pillarWeakness: 'taijutsu',
    lore: 'O primeiro teste de qualquer aspirante. Serve para calibrar a força dos golpes e o ritmo de respiração.',
    avatarType: 'dummy',
    rewardItem: allGameItems.pesos_ferro_negro,
    isDefeated: false,
  },
  {
    id: 'boss_02',
    number: 2,
    name: 'Gato Ladrão dos Telhados',
    title: 'Espírito Veloz da Vila',
    level: 2,
    maxHp: 380,
    currentHp: 380,
    pillarWeakness: 'chakra',
    lore: 'Um felino veloz treinado para roubar pergaminhos de aspirantes desatentos.',
    avatarType: 'shadow_cat',
    rewardItem: allGameItems.talisma_do_fluxo_constante,
    isDefeated: false,
  },
  {
    id: 'boss_03',
    number: 3,
    name: 'Ronin Desertor dos Pinheiros',
    title: 'Guerreiro Errante Sem Mestre',
    level: 4,
    maxHp: 550,
    currentHp: 550,
    pillarWeakness: 'taijutsu',
    lore: 'Abandonou seu dojo para viver nos ermos. Testa a determinação física dos novos Genins.',
    avatarType: 'ronin',
    rewardItem: allGameItems.insignia_da_coragem_silenciosa,
    isDefeated: false,
  },
  {
    id: 'boss_04',
    number: 4,
    name: 'Bibliotecário Fantasma',
    title: 'Guardião dos Arquivos Proibidos',
    level: 6,
    maxHp: 750,
    currentHp: 750,
    pillarWeakness: 'ninjutsu',
    lore: 'Exige que o discípulo prove seu apetite por conhecimento e disciplina mental.',
    avatarType: 'scholar_ghost',
    rewardItem: allGameItems.pergaminho_da_sabedoria_antiga,
    isDefeated: false,
  },
  {
    id: 'boss_05',
    number: 5,
    name: 'Monge do Sino Silencioso',
    title: 'Mestre da Meditação Sob a Névoa',
    level: 8,
    maxHp: 950,
    currentHp: 950,
    pillarWeakness: 'genjutsu',
    lore: 'Medita sob cascatas congeladas. Ele só pode ser atingido por quem domina o silêncio interior.',
    avatarType: 'monk_bell',
    rewardItem: allGameItems.incenso_do_vazio_mental,
    isDefeated: false,
  },
  {
    id: 'boss_06',
    number: 6,
    name: 'Lobo Solitário da Ravina',
    title: 'Sentinela das Montanhas Geladas',
    level: 10,
    maxHp: 1200,
    currentHp: 1200,
    pillarWeakness: 'espirito',
    lore: 'Lidera a matilha com ferocidade serena. Exige coragem sem hesitação para ser superado.',
    avatarType: 'wolf_frost',
    rewardItem: allGameItems.elixir_da_vontade_inquebravel,
    isDefeated: false,
  },
  {
    id: 'boss_07',
    number: 7,
    name: 'Guardião da Ponte Quebrada',
    title: 'Veterano de Cem Cerco',
    level: 12,
    maxHp: 1500,
    currentHp: 1500,
    pillarWeakness: 'chakra',
    lore: 'Bloqueia o avanço rumo ao exame Chunin. Apenas a consistência implacável o dobra.',
    avatarType: 'bridge_guardian',
    rewardItem: allGameItems.pedra_do_selamento_ancestral,
    isDefeated: false,
  },
  {
    id: 'boss_08',
    number: 8,
    name: 'Lança de Bambu Cortante',
    title: 'Mestre do Estilo Fluido',
    level: 14,
    maxHp: 1850,
    currentHp: 1850,
    pillarWeakness: 'taijutsu',
    lore: 'Movimenta-se como o bambu ao vento: flexível, rápido e letal.',
    avatarType: 'spear_master',
    rewardItem: allGameItems.manopla_do_dragao_de_pedra,
    isDefeated: false,
  },
  {
    id: 'boss_09',
    number: 9,
    name: 'Ilusionista dos Espelhos de Fumaça',
    title: 'Enganador dos Sentidos',
    level: 16,
    maxHp: 2200,
    currentHp: 2200,
    pillarWeakness: 'genjutsu',
    lore: 'Cria miragens de fracasso e cansaço mental. Requer foco inquebrável para dissipar.',
    avatarType: 'smoke_illusionist',
    rewardItem: allGameItems.espelho_da_atencao_plena,
    isDefeated: false,
  },
  {
    id: 'boss_10',
    number: 10,
    name: 'Estrategista das Mil Páginas',
    title: 'Comandante da Tática Noturna',
    level: 18,
    maxHp: 2600,
    currentHp: 2600,
    pillarWeakness: 'ninjutsu',
    lore: 'Prevê cada movimento impulsivo. Só pode ser vencido pelo estudo sistemático.',
    avatarType: 'tactician',
    rewardItem: allGameItems.lente_do_estudioso_noturno,
    isDefeated: false,
  },
  {
    id: 'boss_11',
    number: 11,
    name: 'Guerreiro das Sombras Silenciosas',
    title: 'Batedor dos Desfiladeiros Escuros',
    level: 20,
    maxHp: 3000,
    currentHp: 3000,
    pillarWeakness: 'espirito',
    lore: 'Aparece nos momentos de maior dúvida pessoal para testar o espírito de luta.',
    avatarType: 'shadow_scout',
    rewardItem: allGameItems.laminas_gemeas_da_execucao,
    isDefeated: false,
  },
  {
    id: 'boss_12',
    number: 12,
    name: 'Golias de Pedra Vulcânica',
    title: 'Titã da Forja Antiga',
    level: 22,
    maxHp: 3500,
    currentHp: 3500,
    pillarWeakness: 'taijutsu',
    lore: 'O primeiro chefe da fase da Forja. Corpo blindado por basalto e disciplina de ferro.',
    avatarType: 'stone_golem',
    rewardItem: allGameItems.sandalias_do_vento_cortante,
    isDefeated: false,
  },
  {
    id: 'boss_13',
    number: 13,
    name: 'Mestra das Marionetes de Ferro',
    title: 'Condutora de Fios Invisíveis',
    level: 24,
    maxHp: 4000,
    currentHp: 4000,
    pillarWeakness: 'chakra',
    lore: 'Controla suas marionetes com fluxos contínuos de energia sem vacilar um único segundo.',
    avatarType: 'puppeteer',
    rewardItem: allGameItems.talisma_do_fluxo_constante,
    isDefeated: false,
  },
  {
    id: 'boss_14',
    number: 14,
    name: 'Erudito dos Selos Perdidos',
    title: 'Guardião dos Tratados Históricos',
    level: 26,
    maxHp: 4600,
    currentHp: 4600,
    pillarWeakness: 'ninjutsu',
    lore: 'Decifra tomos arcaicos e exige profunda assimilação de leitura.',
    avatarType: 'seal_scholar',
    rewardItem: allGameItems.tomo_dos_cem_fundamentos,
    isDefeated: false,
  },
  {
    id: 'boss_15',
    number: 15,
    name: 'Espírito do Vórtice Noturno',
    title: 'Aparição das Horas Mortas',
    level: 28,
    maxHp: 5200,
    currentHp: 5200,
    pillarWeakness: 'genjutsu',
    lore: 'Tenta alimentar distrações nas horas de descanso e foco profundo.',
    avatarType: 'night_vortex',
    rewardItem: allGameItems.sino_da_clareza_absoluta,
    isDefeated: false,
  },
  {
    id: 'boss_16',
    number: 16,
    name: 'Guerreiro de Armadura de Obsidiana',
    title: 'Vanguarda do Bastião Negro',
    level: 30,
    maxHp: 5900,
    currentHp: 5900,
    pillarWeakness: 'espirito',
    lore: 'Empunha um escudo colossal feito de desculpas e adiamentos. Exige coragem pura.',
    avatarType: 'obsidian_knight',
    rewardItem: allGameItems.estandarte_do_lobo_indomavel,
    isDefeated: false,
  },
  {
    id: 'boss_17',
    number: 17,
    name: 'Comandante da Lâmina Relâmpago',
    title: 'Capitão da Guarda de Tempestade',
    level: 33,
    maxHp: 6700,
    currentHp: 6700,
    pillarWeakness: 'chakra',
    lore: 'Ataques tão rápidos quanto relâmpagos. A única defesa é uma rotina inabalável.',
    avatarType: 'lightning_captain',
    rewardItem: allGameItems.pedra_do_selamento_ancestral,
    isDefeated: false,
  },
  {
    id: 'boss_18',
    number: 18,
    name: 'Mestre da Dança das Oito Lâminas',
    title: 'Instrutor Supremo de Combate',
    level: 36,
    maxHp: 7600,
    currentHp: 7600,
    pillarWeakness: 'taijutsu',
    lore: 'O início da provação Anbu. Treinamento físico de resistência extrema.',
    avatarType: 'blade_dancer',
    rewardItem: allGameItems.manopla_do_dragao_de_pedra,
    isDefeated: false,
  },
  {
    id: 'boss_19',
    number: 19,
    name: 'Corvo Mensageiro das Brumas',
    title: 'Espião das Linhas Inimigas',
    level: 39,
    maxHp: 8600,
    currentHp: 8600,
    pillarWeakness: 'ninjutsu',
    lore: 'Voa entre as brumas carregando enigmas táticos que exigem raciocínio afiado.',
    avatarType: 'mist_crow',
    rewardItem: allGameItems.lente_do_estudioso_noturno,
    isDefeated: false,
  },
  {
    id: 'boss_20',
    number: 20,
    name: 'Sombra do Templo Submerso',
    title: 'Entidade do Silêncio Profundo',
    level: 42,
    maxHp: 9700,
    currentHp: 9700,
    pillarWeakness: 'genjutsu',
    lore: 'Habita as águas calmas onde nenhuma distração pode sobreviver.',
    avatarType: 'temple_shadow',
    rewardItem: allGameItems.incenso_do_vazio_mental,
    isDefeated: false,
  },
  {
    id: 'boss_21',
    number: 21,
    name: 'Senhor dos Portões de Ferro',
    title: 'Último Guardião da Fase da Forja',
    level: 45,
    maxHp: 11000,
    currentHp: 11000,
    pillarWeakness: 'espirito',
    lore: 'Marca a entrada na fase de Mestria dos 66 dias. Abre passagem apenas aos verdadeiros forjados.',
    avatarType: 'gate_lord',
    rewardItem: allGameItems.estandarte_do_lobo_indomavel,
    isDefeated: false,
  },
  {
    id: 'boss_22',
    number: 22,
    name: 'Dragão de Jade Ancestral',
    title: 'Guardião dos Cinco Fluxos',
    level: 48,
    maxHp: 12500,
    currentHp: 12500,
    pillarWeakness: 'chakra',
    lore: 'Espírito venerado que harmoniza todos os 5 pilares do guerreiro.',
    avatarType: 'jade_dragon',
    rewardItem: allGameItems.orbe_do_chakra_infinito,
    isDefeated: false,
  },
  {
    id: 'boss_23',
    number: 23,
    name: 'Mestre da Espada Sem Bainha',
    title: 'Lenda da Precisão Corporal',
    level: 51,
    maxHp: 14200,
    currentHp: 14200,
    pillarWeakness: 'taijutsu',
    lore: 'Seus golpes não desperdiçam um único milímetro de movimento.',
    avatarType: 'sword_saint',
    rewardItem: allGameItems.sandalias_do_vento_cortante,
    isDefeated: false,
  },
  {
    id: 'boss_24',
    number: 24,
    name: 'Guardião do Oráculo Estelar',
    title: 'Visionário do Destino',
    level: 54,
    maxHp: 16000,
    currentHp: 16000,
    pillarWeakness: 'ninjutsu',
    lore: 'Enxerga o padrão dos hábitos como constelações gravadas na mente humana.',
    avatarType: 'star_oracle',
    rewardItem: allGameItems.tomo_dos_cem_fundamentos,
    isDefeated: false,
  },
  {
    id: 'boss_25',
    number: 25,
    name: 'Espelho do Vazio Interior',
    title: 'O Duelo Contra a Própria Mente',
    level: 57,
    maxHp: 18000,
    currentHp: 18000,
    pillarWeakness: 'genjutsu',
    lore: 'Coloca o guerreiro frente a frente com suas próprias desculpas mais profundas.',
    avatarType: 'mirror_void',
    rewardItem: allGameItems.sino_da_clareza_absoluta,
    isDefeated: false,
  },
  {
    id: 'boss_26',
    number: 26,
    name: 'General da Tempestade de Areia',
    title: 'Veterano das Dunas Sem Fim',
    level: 60,
    maxHp: 20500,
    currentHp: 20500,
    pillarWeakness: 'espirito',
    lore: 'Marcha mesmo em tempestades que arrancam árvores pela raiz.',
    avatarType: 'sand_general',
    rewardItem: allGameItems.elixir_da_vontade_inquebravel,
    isDefeated: false,
  },
  {
    id: 'boss_27',
    number: 27,
    name: 'Patriarca do Templo das Sete Montanhas',
    title: 'Ermitão do Fogo Sagrado',
    level: 62,
    maxHp: 23500,
    currentHp: 23500,
    pillarWeakness: 'chakra',
    lore: 'Guarda o segredo da longevidade e da energia inesgotável.',
    avatarType: 'fire_hermit',
    rewardItem: allGameItems.orbe_do_chakra_infinito,
    isDefeated: false,
  },
  {
    id: 'boss_28',
    number: 28,
    name: 'Sannin das Sombras Primordiais',
    title: 'Lenda Viva dos Campos de Batalha',
    level: 64,
    maxHp: 27000,
    currentHp: 27000,
    pillarWeakness: 'taijutsu',
    lore: 'Apenas os mais disciplinados chegam a trocar golpes com ele.',
    avatarType: 'shadow_sannin',
    rewardItem: allGameItems.laminas_gemeas_da_execucao,
    isDefeated: false,
  },
  {
    id: 'boss_29',
    number: 29,
    name: 'Guardião do Trono Celestial',
    title: 'Sentinela do Pico dos 66 Dias',
    level: 65,
    maxHp: 31000,
    currentHp: 31000,
    pillarWeakness: 'ninjutsu',
    lore: 'O último obstáculo antes do reconhecimento absoluto como Kage.',
    avatarType: 'celestial_sentinel',
    rewardItem: allGameItems.lente_da_lenda_forjada,
    isDefeated: false,
  },
  {
    id: 'boss_30',
    number: 30,
    name: 'A Lenda Refletida (O Seu Antigo Eu)',
    title: 'O Soberano da Inércia Superada',
    level: 66,
    maxHp: 36000,
    currentHp: 36000,
    pillarWeakness: 'chakra',
    lore: 'O duelo final dos 66 dias: você enfrenta a personificação de todas as dúvidas e procrastinações do passado, agora subjugadas pela sua mestria.',
    avatarType: 'legend_mirror',
    rewardItem: allGameItems.lente_da_lenda_forjada,
    isDefeated: false,
  }
];
