import { Item } from './types';

export const allGameItems: Record<string, Item> = {
  // Relíquias de Taijutsu (Corpo)
  pesos_ferro_negro: {
    id: 'pesos_ferro_negro',
    name: 'Pesos de Ferro Negro',
    type: 'gear',
    description: 'Faixas pesadas para tornozelos e punhos. Forjam disciplina muscular e resistência.',
    icon: '🏋️‍♂️',
    rarity: 'common',
    buffType: 'xp_boost_pillar',
    buffValue: 15,
    targetPillar: 'taijutsu',
  },
  manopla_do_dragao_de_pedra: {
    id: 'manopla_do_dragao_de_pedra',
    name: 'Manopla do Dragão de Pedra',
    type: 'gear',
    description: 'Manopla forjada com resíduo vulcânico. Maximiza a energia gasta em esforços físicos.',
    icon: '🥊',
    rarity: 'rare',
    buffType: 'xp_boost_pillar',
    buffValue: 25,
    targetPillar: 'taijutsu',
  },
  sandalias_do_vento_cortante: {
    id: 'sandalias_do_vento_cortante',
    name: 'Sandálias do Vento Cortante',
    type: 'gear',
    description: 'Aumenta agilidade corporal e postura durante treinos intensos.',
    icon: '🥿',
    rarity: 'epic',
    buffType: 'xp_boost_pillar',
    buffValue: 35,
    targetPillar: 'taijutsu',
  },

  // Relíquias de Ninjutsu (Mente)
  pergaminho_da_sabedoria_antiga: {
    id: 'pergaminho_da_sabedoria_antiga',
    name: 'Pergaminho da Sabedoria Antiga',
    type: 'scroll',
    description: 'Texto preservado em seda pura que expande a retenção de leitura e estudos.',
    icon: '📜',
    rarity: 'common',
    buffType: 'xp_boost_pillar',
    buffValue: 15,
    targetPillar: 'ninjutsu',
  },
  lente_do_estudioso_noturno: {
    id: 'lente_do_estudioso_noturno',
    name: 'Lente do Estudioso Noturno',
    type: 'gear',
    description: 'Melhora a absorção de conhecimento denso e leitura profunda.',
    icon: '🧐',
    rarity: 'rare',
    buffType: 'xp_boost_pillar',
    buffValue: 25,
    targetPillar: 'ninjutsu',
  },
  tomo_dos_cem_fundamentos: {
    id: 'tomo_dos_cem_fundamentos',
    name: 'Tomo dos Cem Fundamentos',
    type: 'scroll',
    description: 'Um tratado monumental de estratégia e lógica prática.',
    icon: '📖',
    rarity: 'epic',
    buffType: 'xp_boost_pillar',
    buffValue: 35,
    targetPillar: 'ninjutsu',
  },

  // Relíquias de Chakra (Disciplina / Consistência)
  talisma_do_fluxo_constante: {
    id: 'talisma_do_fluxo_constante',
    name: 'Talismã do Fluxo Constante',
    type: 'relic',
    description: 'Harmoniza os horários diários e reforça a precisão da rotina.',
    icon: '⚡',
    rarity: 'common',
    buffType: 'xp_boost_pillar',
    buffValue: 15,
    targetPillar: 'chakra',
  },
  pedra_do_selamento_ancestral: {
    id: 'pedra_do_selamento_ancestral',
    name: 'Pedra de Selamento Ancestral',
    type: 'relic',
    description: 'Armazena energia residual de disciplina. Concede 1 Escudo de Falha extra na semana.',
    icon: '💠',
    rarity: 'rare',
    buffType: 'extra_shield',
    buffValue: 1,
  },
  orbe_do_chakra_infinito: {
    id: 'orbe_do_chakra_infinito',
    name: 'Orbe do Chakra Infinito',
    type: 'relic',
    description: 'A consistência se torna inabalável. Bônus massivo em tarefas de disciplina.',
    icon: '🔮',
    rarity: 'legendary',
    buffType: 'xp_boost_pillar',
    buffValue: 40,
    targetPillar: 'chakra',
  },

  // Relíquias de Espírito (Confiança / Coragem)
  insignia_da_coragem_silenciosa: {
    id: 'insignia_da_coragem_silenciosa',
    name: 'Insígnia da Coragem Silenciosa',
    type: 'relic',
    description: 'Forjada em bronze escuro. Estimula a superação de medos e desconfortos.',
    icon: '🛡️',
    rarity: 'common',
    buffType: 'xp_boost_pillar',
    buffValue: 15,
    targetPillar: 'espirito',
  },
  elixir_da_vontade_inquebravel: {
    id: 'elixir_da_vontade_inquebravel',
    name: 'Elixir da Vontade Inquebrável',
    type: 'elixir',
    description: 'Destilado aromático de ervas de montanha que renova a autoconfiança.',
    icon: '🧪',
    rarity: 'rare',
    buffType: 'xp_boost_pillar',
    buffValue: 25,
    targetPillar: 'espirito',
  },
  estandarte_do_lobo_indomavel: {
    id: 'estandarte_do_lobo_indomavel',
    name: 'Estandarte do Lobo Indomável',
    type: 'relic',
    description: 'Símbolo dos guerreiros que nunca aceitam a derrota.',
    icon: '🐺',
    rarity: 'epic',
    buffType: 'xp_boost_pillar',
    buffValue: 35,
    targetPillar: 'espirito',
  },

  // Relíquias de Genjutsu (Foco / Concentração)
  incenso_do_vazio_mental: {
    id: 'incenso_do_vazio_mental',
    name: 'Incenso do Vazio Mental',
    type: 'relic',
    description: 'Dispersa distrações digitais e induz estado de fluxo imediato.',
    icon: '🕯️',
    rarity: 'common',
    buffType: 'xp_boost_pillar',
    buffValue: 15,
    targetPillar: 'genjutsu',
  },
  espelho_da_atencao_plena: {
    id: 'espelho_da_atencao_plena',
    name: 'Espelho da Atenção Plena',
    type: 'relic',
    description: 'Reflete apenas a verdade do momento presente. Amplia o rendimento do Deep Work.',
    icon: '🪞',
    rarity: 'rare',
    buffType: 'xp_boost_pillar',
    buffValue: 25,
    targetPillar: 'genjutsu',
  },
  sino_da_clareza_absoluta: {
    id: 'sino_da_clareza_absoluta',
    name: 'Sino da Clareza Absoluta',
    type: 'relic',
    description: 'Seu soar dissipa qualquer névoa mental e bloqueia a procrastinação.',
    icon: '🔔',
    rarity: 'legendary',
    buffType: 'xp_boost_pillar',
    buffValue: 40,
    targetPillar: 'genjutsu',
  },

  // Relíquias Globais e Bônus de Dano
  lente_da_lenda_forjada: {
    id: 'lente_da_lenda_forjada',
    name: 'Lente da Lenda Forjada',
    type: 'relic',
    description: 'Relíquia lendária que aumenta todo o XP obtido em qualquer missão.',
    icon: '✨',
    rarity: 'legendary',
    buffType: 'xp_boost_all',
    buffValue: 20,
  },
  laminas_gemeas_da_execucao: {
    id: 'laminas_gemeas_da_execucao',
    name: 'Lâminas Gêmeas da Execução',
    type: 'gear',
    description: 'Aumenta o dano causado aos adversários do Modo Duelo em +30%.',
    icon: '⚔️',
    rarity: 'rare',
    buffType: 'damage_boost',
    buffValue: 30,
  },
};
